<a href="https://colab.research.google.com/github/jan-podlipny/Machine-Learning-notes/blob/master/einsum.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import torch as t

In [90]:
A = np.array([0, 1, 2])

B = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
 

In [91]:
#view of A
print(np.einsum('i',A))
#sum of elements in A (->)
print(np.einsum('i->',A))

[0 1 2]
3


In [92]:
print(np.einsum('ij',B))
print(f"Sum along columns {np.einsum('ij->i',B)}")
print(f"Sum along rows {np.einsum('ij->j',B)}")
print(f"Sum all elements {np.einsum('ij->',B)}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Sum along columns [ 6 22 38]
Sum along rows [12 15 18 21]
Sum all elements 66


In [95]:
#element wise multiplication and sum along columns
print((A[:, np.newaxis] * B).sum(axis=1))
print(np.einsum('i,ij->i',A, B))

[ 0 22 76]
[ 0 22 76]


In [121]:
A = np.array([[1, 1, 1],
              [2, 2, 2],
              [5, 5, 5]])

B = np.array([[0, 1, 0],
              [1, 1, 0],
              [1, 1, 1]])

In [138]:
#transpose A
np.einsum('ji',A)

array([[1, 2, 5],
       [1, 2, 5],
       [1, 2, 5]])

In [140]:
#main diagonal of A
np.einsum('ii->i',A)

array([1, 2, 5])

In [142]:
#trace of A (sum of diagonal)
np.einsum('ii',A)

8

In [143]:
#matrix multiplication
A @ B

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [152]:
np.einsum('ij,jk->ik', A, B)

array([[ 2,  3,  1],
       [ 4,  6,  2],
       [10, 15,  5]])

In [156]:
#element-wise multiplication of A and B.T
np.einsum('ij,ji->ij',A,B)

array([[0, 1, 1],
       [2, 2, 2],
       [0, 0, 5]])

In [119]:
#matrix multiplication
A @ B

array([[ 2,  3,  1],
       [ 5,  7,  2],
       [10, 15,  5]])