In [207]:
import numpy as np

In [208]:
X = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12],[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [209]:
x_train = np.array([[2,3,4,5], [6,7,8,9], [10,11,12,13]])

In [210]:
X.shape,x_train.shape

((6, 4), (3, 4))

In [211]:
X.shape[0]

6

In [212]:
X[1,:]

array([5, 6, 7, 8])

In [213]:
X

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [214]:
dists = np.zeros((x_num, x_train_num))

In [215]:
for i in range(x_train.shape[0]):
    for j in range(X.shape[0]):
        dists[i,j] = np.sqrt(np.sum(((X[j,:]- x_train[i,:])**2)))
        print(X[j,:],x_train[i,:],dists[i,j])
        

[1 2 3 4] [2 3 4 5] 2.0
[5 6 7 8] [2 3 4 5] 6.0
[ 9 10 11 12] [2 3 4 5] 14.0
[1 2 3 4] [2 3 4 5] 2.0
[5 6 7 8] [2 3 4 5] 6.0
[ 9 10 11 12] [2 3 4 5] 14.0
[1 2 3 4] [6 7 8 9] 10.0
[5 6 7 8] [6 7 8 9] 2.0
[ 9 10 11 12] [6 7 8 9] 6.0
[1 2 3 4] [6 7 8 9] 10.0
[5 6 7 8] [6 7 8 9] 2.0
[ 9 10 11 12] [6 7 8 9] 6.0
[1 2 3 4] [10 11 12 13] 18.0
[5 6 7 8] [10 11 12 13] 10.0
[ 9 10 11 12] [10 11 12 13] 2.0
[1 2 3 4] [10 11 12 13] 18.0
[5 6 7 8] [10 11 12 13] 10.0
[ 9 10 11 12] [10 11 12 13] 2.0


In [223]:
dists2 = np.zeros((x_num, x_train_num))

In [224]:
for i in range(x_train.shape[0]):
    dists2[i,:] = np.sqrt(np.sum((x_train[i,:] - X)**2,axis = 1))

In [225]:
for e in dists2:
    print(e)

[ 2.  6. 14.  2.  6. 14.]
[10.  2.  6. 10.  2.  6.]
[18. 10.  2. 18. 10.  2.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]


In [220]:
dists - dists2


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [80]:
cot = 0
for i in range(500):
    for j in range(5000):
        c[i,j] = cot
        cot += 1

In [98]:
c[0].shape

(5000,)

In [97]:
X-x_train

array([[-1, -1, -1, -1],
       [-1, -1, -1, -1],
       [-1, -1, -1, -1]])

In [101]:
c[499,4999]

2499999.0

In [102]:
c.shape

(500, 5000)

In [103]:
for i in range(5):
    print(i)

0
1
2
3
4
